name: rust-test

on: 
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env: 
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-A dead_code -A unused_imports"

jobs:
  test:
    runs-on: ubutunt-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --lib --bins --tests 
